defmodule BlargData.Films.Atragon1963 do
  import DataUtil

  def get do
    %{
      title: "Atragon",
      path: "atragon-1963",
      original_title: "海底軍艦",
      transliteration: "Kaitei Gunkan",
      translation: "Undersea Warship",
      release_date: generate_date(1963, 12, 22),
      runtime: 94,
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Screenplay", "Shinichi Sekizawa"},
        {"Original Story", "Shunro Oshikawa"},
        {"Photography", "Hajime Koizumi"},
        {"Art", "Takeo Kita"},
        {"Sound", "Masanao Uehara"},
        {"Lighting", "Shoshichi Kojima"},
        {"Music", "Akira Ifukube"},
        {"Editor", "Ryohei Fujii"},
        {"Special Effects Photography", "Sadamasa Arikawa"},
        {"Special Effects Assistant Director", "Teruyoshi Nakano"}
      ],
      top_billed_cast: [
        {"Tadao Takashima", "Susumu Hatanaka"},
        {"Yoko Fujiyama", "Makoto Jinguji"},
        {"Yu Fujiki", "Yoshito Nishibe"},
        {"Kenji Sahara", "Unno"},
        {"Ken Uehara", "Admiral Kusumi"},
        {"Hiroshi Koizumi", "Detective Ito"},
        {"Jun Tazaki", "Captain Hachiro Jinguji"},
        {"Yoshibumi Tajima", "Lt. Amano"},
        {"Akihiko Hirata", "Mu Agent No. 23"},
        {"Hideyo Amamoto", "High Priest of Mu"},
        {"Susumu Fujita", "General"},
        {"Minoru Takada", "Military Officer"},
        {"Hisaya Ito", "Kidnapped Scientist"},
        {"Ikio Sawamura", "Taxi Driver"},
        {"Tetsuko Kobayashi", "Empress of Mu"},
        {"Hiroshi Hasegawa", "Atragon Crew"},
        {"Nadao Kirino", "Kidnapped Scientist"},
        {"Shin Otomo", "Military Officer"},
        {"Haruya Sakamoto", "Atragon Crew"},
        {"Tetsu Nakamura", "Cargo Ship Captain"},
        {"Yutaka Nakayama", "Cargo Ship Crew"},
        {"Mitsuo Tsuda", "Military Officer"},
        {"Koji Uno", "Policeman"},
        {"Rinsaku Ogata", "Military Officer"},
        {"Yutaka Oka", "Mihara Tourist"},
        {"Yukihiko Gondo", "Mihara Tourist"},
        {"Shoichi Hirose", "Mu Citizen"},
        {"Katsumi Tezuka", "Military Officer"},
        {"Takuzo Kumagai", "Military Officer"},
        {"Shiro Tsuchiya", "Atragon Crew"},
        {"Wataru Omae", "Soldier"},
        {"Hideo Shibuya", "Soldier"},
        {"Keisuke Yamada", "Military Officer"}
      ],
      other_cast: [
        {"Kazuo Hinata", "Military Officer"},
        {"Yoshio Katsube", "Atragon Crew"},
        {"Kenichiro Maruyama", "Cargo Ship Crew"},
        {"Haruo Nakajima", "Military Officer"},
        {"Tadashi Okabe", "Policeman"},
        {"Masaki Shinohara", "Mihara Tourist"},
        {"Haruo Suzuki", "Atragon Crew"},
        {"Osman Yusef", "Mu Soldier"}
      ],
      credits: generate_credits("atragon_1963"),
      synopsis: generate_synopsis("atragon_1963"),
      images: [
        "00049",
        "00208",
        "00542",
        "00554",
        "00568",
        "00581",
        "00585",
        "00624",
        "00684",
        "00886",
        "00903",
        "00987",
        "01009",
        "01207",
        "01393",
        "01444",
        "01449",
        "01541",
        "01547",
        "01629",
        "01810",
        "01825",
        "02236",
        "02249",
        "02392",
        "02403",
        "02451",
        "02551",
        "02561",
        "02618",
        "02622",
        "02649",
        "02676",
        "02746",
        "02755",
        "02758"
      ]
    }
  end
end
