defmodule BlargData.Films.BattleInOuterSpace1959 do
  import DataUtil

  def get do
    %{
      title: "Battle in Outer Space",
      path: "battle-in-outer-space-1959",
      original_title: "宇宙大戦争",
      transliteration: "Uchū Daisensō",
      translation: "Space Great War",
      release_date: generate_date(1959, 12, 26),
      runtime: 91,
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Original Story", "Jojiro Okami"},
        {"Screenplay", "Shinichi Sekizawa"},
        {"Photography", "Hajime Koizumi"},
        {"Art", "Teruaki Abe"},
        {"Lighting", "Rokuro Ishikawa"},
        {"Sound", ["Choshichiro Mikami", "Masanobu Miyazaki"]},
        {"Music", "Akira Ifukube"},
        {"Editor", "Kazuji Taira"},
        {"Special Effects Photography", "Sadamasa Arikawa"}
      ],
      top_billed_cast: [
        {"Ryo Ikebe", "Major Ichiro Katsumiya"},
        {"Kyoko Anzai", "Etsuko Shiraishi"},
        {"Minoru Takada", "Defense Commander"},
        {"Koreya Senda", "Dr. Adachi"},
        {"Len Stanford", "Dr. Richardson"},
        {"Harold S. Conway", "Dr. Immelman"},
        {"George Wyman", "Dr. Ahmed"},
        {"Elise Richter", "Sylvia"},
        {"Hisaya Ito", "Astronaut Kogure"},
        {"Yoshio Tsuchiya", "Astronaut Iwamura"},
        {"Nadao Kirino", "Astronaut Okada"},
        {"Kozo Nomura", "Space Jet Pilot"},
        {"Fuyuki Murakami", "Detective Iriake"},
        {"Ikio Sawamura", "Line Inspector"},
        {"Takuzo Kumagai", "Military Officer"},
        {"Katsumi Tezuka", "Military Officer"},
        {"Mitsuo Tsuda", "Military Officer"},
        {"Tadashi Okabe", "Military Officer"},
        {"Osman Yusef", "Astronaut"},
        {"Yasuhisa Tsutsumi", "Train Conductor"},
        {"Rinsaku Ogata", "Astronaut"},
        {"Keisuke Yamada", "UN Official"},
        {"Yutaka Oka", "Astronaut"},
        {"Shigeo Kato", "Train Conductor"},
        {"Yukihiko Gondo", "Space Station Crew"}
      ],
      other_cast: [
        {"Kazuo Hinata", "UN Official"},
        {"Andrew Hughes", "UN Official"},
        {"Saburo Iketani", "Newsreader"},
        {"Minoru Ito", "Speaker"},
        {"Yoshio Katsube", "Attendant"},
        {"Junichiro Mukai", "Policeman"},
        {"Keiji Sakakida", "UN Official"},
        {"Haruya Sakamoto", "Policeman"},
        {"Haruo Suzuki", "Detective"},
        {"Obel Wyatt", "Military Officer"}
      ],
      credits: generate_credits("battle_in_outer_space_1959"),
      synopsis: generate_synopsis("battle_in_outer_space_1959"),
      images: [
        "00043",
        "00209",
        "00376",
        "00473",
        "00662",
        "00851",
        "00868",
        "01045",
        "01116",
        "01525",
        "01580",
        "01717",
        "01873",
        "02037",
        "02263",
        "02325",
        "02353",
        "02394",
        "02445",
        "02460",
        "02505",
        "02517",
        "02550",
        "02559",
        "02607",
        "02633",
        "02696"
      ]
    }
  end
end
