defmodule BlargData.Films.BirthOfJapan1959 do
  import DataUtil

  def get do
    %{
      title: "The Birth of Japan",
      path: "birth-of-japan-1959",
      original_title: "日本誕生",
      transliteration: "Nihon Tanjō",
      translation: "Birth of Japan",
      aliases: "The Three Treasures",
      release_date: generate_date(1959, 10, 25),
      runtime: 182,
      produced_by: "Toho",
      staff: [
        {"Director", "Hiroshi Inagaki"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", ["Sanezumi Fujimoto", "Tomoyuki Tanaka"]},
        {"Screenplay", ["Toshio Yasumi", "Ryuzo Kikushima"]},
        {"Art Director", "Kisaku Ito"},
        {"Photography", "Kazuo Yamada"},
        {"Music", "Akira Ifukube"},
        {"Sound", ["Yoshio Nishikawa", "Hisashi Shimonaga"]},
        {"Lighting", "Shoshichi Kojima"},
        {"Editor", "Kazuji Taira"},
        {"Special Effects Photography", "Sadamasa Arikawa"}
      ],
      top_billed_cast: [
        {"Toshiro Mifune", ["Prince Ousu", "Susano-o"]},
        {"Yoko Tsukasa", "Oto Tachibana"},
        {"Kumi Mizuno", "Azami"},
        {"Misa Uehara", "Kushinada"},
        {"Kyoko Kagawa", "Princess Miyazu"},
        {"Kinuyo Tanaka", "Prince Yamato"},
        {"Nobuko Otowa", "Dancing Goddess"},
        {"Haruko Sugimura", "Storyteller"},
        {"Akira Kubo", "Prince Ioki"},
        {"Akira Takarada", "Prince Wakatarashi"},
        {"Ganjiro Nakamura", "Emperor Keiko"},
        {"Eijiro Tono", "Otomo"},
        {"Akihiko Hirata", "Takehiko"},
        {"Ko Mishima", "Yakumo"},
        {"Hisaya Ito", "Kodate Otomo"},
        {"Jun Tazaki", "Kurohiko"},
        {"Takashi Shimura", "Elder Kumaso"},
        {"Kichijiro Ueda", "Hachihara"},
        {"Yoshio Kosugi", "Inaba"},
        {"Kozo Nomura", "Makeri Otomo"},
        {"Yu Fujiki", "Kojikahi"},
        {"Keiko Muramatsu", "Izanami"},
        {"Chieko Nakakita", "Tenazuchi"},
        {"Bokuzen Hidari", "Diety"},
        {"Minosuke Yamada", "Okuri"},
        {"Akira Sera", "Anazuchi"},
        {"Hajime Izu", "Prince Oji"},
        {"Yoshibumi Tajima", "Deity"},
        {"Fuyuki Murakami", "Deity"},
        {"Akira Tani", "Deity"},
        {"Junichiro Mukai", "Moroto"},
        {"Ikio Sawamura", "Deity"},
        {"Senkichi Omura", "Yamato Villager"},
        {"Yutaka Sada", "Yamato Villager"},
        {"Mitsuo Tsuda", "Yamato Soldier"},
        {"Nadao Kirino", "Yamato Soldier"},
        {"Shin Otomo", "Kumaso Soldier"},
        {"Shoichi Hirose", "Kumaso Soldier"},
        {"Shiro Tsuchiya", "Yamato Soldier"},
        {"Fuminto Matsuo", "Yamato Villager"},
        {"Yasuhisa Tsutsumi", "Yamato Soldier"},
        {"Takuzo Kumagai", "Yamato Villager"},
        {"Haruya Sakamoto", "Yamato Soldier"},
        {"Rinsaku Ogata", "Yamato Soldier"},
        {"Hiroyuki Wakita", "Izanagi"},
        {"Hideyo Amamoto", "Deity"},
        {"Keiju Kobayashi", "Amatsumara"},
        {"Daisuke Kato", "Futodama"},
        {"Norihei Miki", "Koyane"},
        {"Ichiro Arishima", "Ridouri"},
        {"Kingoro Yanagiya", "Omoikane"},
        {"Kenichi Enomoto", "Tamaso"},
        {"Taro Asahiyo", "Tajikarao"},
        {"Koji Tsuruta", "Younger Kumaso"},
        {"Setsuko Hara", "Amaterasu"}
      ],
      other_cast: [
        {"Ken Echigo", "Yamato Soldier"},
        {"Yukihiko Gondo", "Yamato Villager"},
        {"Kazuo Hinata", "Utte Villager"},
        {"Naoya Kusakawa", "Utte Soldier"},
        {"Akio Kusama", ["Deity", "Yamato Villager"]},
        {"Junpei Natsuki", "Owari Villager"},
        {"Yutaka Oka", "Deity"},
        {"Keiji Sakakida", "Yamato Villager"},
        {"Masaaki Tachibana", "Yamato Soldier"},
        {"Kamayuki Tsubono", "Otomo Soldier"},
        {"Ren Yamamoto", "Yamato Soldier"}
      ],
      credits: generate_credits("birth_of_japan_1959"),
      synopsis: generate_synopsis("birth_of_japan_1959"),
      images: [
        "00125",
        "00143",
        "00149",
        "00224",
        "00330",
        "00351",
        "00385",
        "00427",
        "00482",
        "00514",
        "00544",
        "00660",
        "00739",
        "00848",
        "00853",
        "00924",
        "00939",
        "00976",
        "01008",
        "01075",
        "01093",
        "01101",
        "01258",
        "01326",
        "01542",
        "01667",
        "01824",
        "01971",
        "02140",
        "02216",
        "02290",
        "02647",
        "02793",
        "02997",
        "03115",
        "03253",
        "03464",
        "03627",
        "03904",
        "04186",
        "04202",
        "04322",
        "04808",
        "04898",
        "05017",
        "05151",
        "05193",
        "05262",
        "05376"
      ]
    }
  end
end
