defmodule BlargData.Films.DestroyAllMonsters1968 do
  import DataUtil

  def get do
    %{
      title: "Destroy All Monsters",
      path: "destroy-all-monsters-1968",
      original_title: "怪獣総進撃",
      transliteration: "Kaijū Sōshingeki",
      translation: "Monster Marching Attack",
      release_date: generate_date(1968, 8, 1),
      runtime: 89,
      preceded_by: {"Son of Godzilla", 1967},
      followed_by: {"Godzilla's Revenge", 1971},
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Sadamasa Arikawa"},
        {"Special Effects Supervisor", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Screenplay", ["Takeshi Kimura", "Ishiro Honda"]},
        {"Photography", "Taiichi Kankura"},
        {"Art", "Takeo Kita"},
        {"Sound", "Shoichi Yoshizawa"},
        {"Lighting", "Seiji Hirano"},
        {"Music", "Akira Ifukube"},
        {"Editor", "Ryohei Fujii"},
        {"Special Effects Art", "Yasuyuki Inoue"},
        {"Special Effects Assistant Director", "Teruyoshi Nakano"}
      ],
      top_billed_cast: [
        {"Akira Kubo", "Katsuo Yamabe"},
        {"Yukiko Kobayashi", "Kyoko Manabe"},
        {"Kyoko Ai", "Kilaak Queen"},
        {"Jun Tazaki", "Dr. Yoshido"},
        {"Yoshio Tsuchiya", "Dr. Otani"},
        {"Kenji Sahara", "Moon Base Commander Nishikawa"},
        {"Susumu Kurobe", "Possessed Monster Island Tech"},
        {"Hisaya Ito", "Major Tada"},
        {"Yoshibumi Tajima", "Defense Chief Sugiyama"},
        {"Nadao Kirino", "Special Police"},
        {"Naoya Kusakawa", "Special Police"},
        {"Ikio Sawamura", "Mountaineer"},
        {"Wataru Omae", "SY-3 Pilot"},
        {"Kazuo Suzuki", "Possessed Monster Island Tech"},
        {"Yutaka Sada", "Village Policeman"},
        {"Chotaro Togin", "SY-3 Pilot Ogata"},
        {"Yasuhiko Saijo", "SY-3 Pilot"},
        {"Seishiro Kuno", "SY-3 Pilot"},
        {"Kenichiro Maruyama", "Moon Base Tech"},
        {"Toru Ibuki", "Possessed Monster Island Tech"},
        {"Ken Echigo", "SY-3 Pilot"},
        {"Minoru Ito", "Possessed Monster Island Tech"},
        {"Hideo Shibuya", "Reporter"},
        {"Yoshio Katsube", "UNSC Tech"},
        {"Kamayuki Tsubono", "Special Police"},
        {"Tadashi Okabe", "Mt. Fuji Reporter"},
        {"Haruya Sakamoto", "Military Advisor"},
        {"Rinsaku Ogata", "Military Advisor"},
        {"Yukihiko Gondo", "Soldier"},
        {"Yutaka Oka", "Reporter"},
        {"Haruo Nakajima", ["Godzilla", "Military Advisor"]},
        {"Hiroshi Sekita", ["Anguirus", "Gorosaurus"]},
        {"Teruo Aragaki", "Rodan"},
        {"Susumu Utsumi", "King Ghidorah"},
        {"Little Man Machan", "Minya"},
        {"Saburo Iketani", "Radio Announcer"},
        {"Henry Okawa", "UNSC Scientist"},
        {"Andrew Hughes", "Dr. Stevenson"}
      ],
      other_cast: [
        {"Kazuo Hinata", "Military Advisor"},
        {"Takuzo Kumagai", "Reporter"},
        {"Akio Kusama", ["Monster Island Tech", "Military Advisor"]},
        {"Junpei Natsuki", "Military Advisor"},
        {"Masaaki Tachibana", "Military Advisor"},
        {"Soji Ubukata", "Reporter"}
      ],
      credits: generate_credits("destroy_all_monsters_1968"),
      synopsis: generate_synopsis("destroy_all_monsters_1968"),
      images: [
        "00020",
        "00093",
        "00113",
        "00123",
        "00188",
        "00210",
        "00212",
        "00350",
        "00431",
        "00432",
        "00528",
        "00731",
        "00780",
        "00945",
        "01061",
        "01109",
        "01114",
        "01165",
        "01349",
        "01355",
        "01360",
        "01420",
        "01479",
        "01616",
        "01630",
        "01669",
        "01824",
        "01966",
        "02039",
        "02099",
        "02236",
        "02287",
        "02370",
        "02474",
        "02600",
        "02624",
        "02627",
        "02647",
        "02653"
      ]
    }
  end
end
