defmodule BlargData.Films.DogoraTheSpaceMonster1964 do
  import DataUtil

  def get do
    %{
      title: "Dogora, the Space Monster",
      path: "dogora-the-space-monster-1964",
      original_title: "宇宙大怪獣ドゴラ",
      transliteration: "Uchū Daikaijū Dogora",
      translation: "Space Giant Monster Dogora",
      aliases: "Dogora",
      release_date: generate_date(1964, 8, 11),
      runtime: 81,
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", ["Tomoyuki Tanaka", "Yasuyoshi Tajitsu"]},
        {"Original Story", "Jojiro Okami"},
        {"Screenplay", "Shinichi Sekizawa"},
        {"Photography", "Hajime Koizumi"},
        {"Art", "Takeo Kita"},
        {"Sound", "Fumio Yanoguchi"},
        {"Lighting", "Shoshichi Kojima"},
        {"Music", "Akira Ifukube"},
        {"Editor", "Ryohei Fujii"},
        {"Special Effects Photography", "Sadamasa Arikawa"},
        {"Special Effects Assistant Director", "Teruyoshi Nakano"}
      ],
      top_billed_cast: [
        {"Yosuke Natsuki", "Detective Komai"},
        {"Yoko Fujiyama", "Masayo Kirino"},
        {"Hiroshi Koizumi", "Dr. Kirino"},
        {"Akiko Wakabayashi", "Hamako"},
        {"Nobuo Nakamura", "Dr. Munakata"},
        {"Seizaburo Kawazu", "Gang Leader"},
        {"Robert Dunham", "Mark Jackson"},
        {"Susumu Fujita", "General Iwata"},
        {"Jun Tazaki", "Police Chief"},
        {"Yoshibumi Tajima", "Gangster"},
        {"Hideyo Amamoto", "Gangster"},
        {"Nadao Kirino", "Gangster"},
        {"Akira Wakamatsu", "Gangster"},
        {"Haruya Kato", "Gangster"},
        {"Jun Funato", "Detective Nitta"},
        {"Yasuhisa Tsutsumi", "Policeman"},
        {"Mitsuo Tsuda", "Soldier"},
        {"Takuzo Kumagai", "Military Advisor"},
        {"Chotaro Togin", "Truck Driver"},
        {"Shoichi Hirose", "Coal Miner"},
        {"Yutaka Nakayama", "Coal Miner"},
        {"Shiro Tsuchiya", "Coal Miner"},
        {"Haruya Sakamoto", "Truck Driver"},
        {"Hideo Shibuya", "Reporter"},
        {"Yutaka Oka", "Coal Miner"},
        {"Tadashi Okabe", "Policeman"},
        {"Wataru Omae", "Satellite Technician"},
        {"Koji Uno", "Coal Miner"}
      ],
      other_cast: [
        {"Ken Echigo", "Soldier"},
        {"Yukihiko Gondo", "Train Attendant"},
        {"Yoshio Katsube", "Satellite Technician"},
        {"Akio Kusama", "Soldier"},
        {"Rinsaku Ogata", "Soldier"},
        {"Haruo Suzuki", "Soldier"},
        {"Masaaki Tachibana", "Soldier"},
        {"Kamayuki Tsubono", "Detective"},
        {"Keisuke Yamada", "Soldier"}
      ],
      credits: generate_credits("dogora_the_space_monster_1964"),
      synopsis: generate_synopsis("dogora_the_space_monster_1964"),
      images: [
        "00029",
        "00067",
        "00182",
        "00464",
        "00591",
        "00829",
        "01129",
        "01417",
        "01589",
        "01636",
        "01660",
        "01672",
        "01765",
        "01998",
        "02034",
        "02143",
        "02215",
        "02223",
        "02256",
        "02395"
      ]
    }
  end
end
