defmodule BlargData.Films.FrankensteinConquersTheWorld1965 do
  import DataUtil

  def get do
    %{
      title: "Frankenstein Conquers the World",
      path: "frankenstein-conquers-the-world-1965",
      original_title: "フランケンシュタイン対地底怪獣バラゴン",
      transliteration: "Furankenshutain Tai Chitei Kaijū Baragon",
      translation: "Frankenstein Against Underground Monster Baragon",
      aliases: "Frankenstein vs. Baragon",
      release_date: generate_date(1965, 8, 8),
      runtime: 94,
      followed_by: {"War of the Gargantuas", 1966},
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Screenplay", "Takeshi Kimura"},
        {"Photography", "Hajime Koizumi"},
        {"Art", "Takeo Kita"},
        {"Sound", "Wataru Konuma"},
        {"Lighting", "Shoshichi Kojima"},
        {"Music", "Akira Ifukube"},
        {"Editor", "Ryohei Fujii"},
        {"Special Effects Photography", "Sadamasa Arikawa"},
        {"Special Effects Assistant Director", "Teruyoshi Nakano"}
      ],
      top_billed_cast: [
        {"Tadao Takashima", "Dr. Yuzo Kawaji"},
        {"Nick Adams", "Dr. James Bowen"},
        {"Kumi Mizuno", "Dr. Sueko Togami"},
        {"Yoshio Tsuchiya", "Kawai"},
        {"Koji Furuhata", "Frankenstein"},
        {"Jun Tazaki", "Officer Nishi"},
        {"Susumu Fujita", "Osaka Police Chief"},
        {"Takashi Shimura", "Axis Scientist"},
        {"Nobuo Nakamura", "Skeptical Museum Curator"},
        {"Kenji Sahara", "Policeman"},
        {"Hisaya Ito", "Policeman"},
        {"Yoshibumi Tajima", "Axis Submarine Captain"},
        {"Kozo Nomura", "Reporter"},
        {"Haruya Kato", "TV Reporter"},
        {"Ikio Sawamura", "Man Walking Dog"},
        {"Yoshio Kosugi", "Soldier"},
        {"Keiko Sawai", "Kazuko"},
        {"Peter Mann", "Dr. Liesendorf"},
        {"Ren Yamamoto", "Kawai's Assistant"},
        {"Yutaka Sada", "Laboratory Administrator"},
        {"Kenzo Tabu", "Skeptical Reporter"},
        {"Shigeki Ishida", "Skeptical Scientist"},
        {"Haruo Nakajima", "Baragon"},
        {"Yutaka Nakayama", "TV Reporter"},
        {"Senkichi Omura", "TV Cameraman"},
        {"Nadao Kirino", "Policeman"},
        {"Yasuhiko Saijo", "Reporter"},
        {"Shin Otomo", "Policeman"},
        {"Shoichi Hirose", "Miner"},
        {"Junichiro Mukai", "Village Policeman"},
        {"Mitsuo Tsuda", "Miner"},
        {"Hideo Shibuya", "Reporter"},
        {"Masaaki Tachibana", "Reporter"},
        {"Tadashi Okabe", "Reporter"},
        {"Rinsaku Ogata", "Soldier"}
      ],
      other_cast: [
        {"Kazuo Hinata", "Reporter"},
        {"Minoru Ito", "Scientist"},
        {"Yoshio Katsube", "Bystander"},
        {"Akio Kusama", "Policeman"},
        {"Junpei Natsuki", "Villager"},
        {"Keiji Sakakida", "Scientist"},
        {"Haruya Sakamoto", "Axis Soldier"},
        {"Haruo Suzuki", "Reporter"},
        {"Kamayuki Tsubono", "Policeman"}
      ],
      credits: generate_credits("frankenstein_conquers_the_world_1965"),
      synopsis: generate_synopsis("frankenstein_conquers_the_world_1965"),
      images: [
        "00067",
        "00196",
        "00267",
        "00273",
        "00521",
        "00695",
        "00705",
        "00778",
        "00838",
        "01032",
        "01070",
        "01097",
        "01172",
        "01239",
        "01500",
        "01722",
        "02039",
        "02168",
        "02284",
        "02620",
        "02668",
        "02691",
        "02726",
        "02752",
        "02755",
        "02777"
      ]
    }
  end
end
