defmodule BlargData.Films.GhidorahTheThreeHeadedMonster1964 do
  import DataUtil

  def get do
    %{
      title: "Ghidorah, the Three-Headed Monster",
      path: "ghidorah-the-three-headed-monster-1964",
      original_title: "三大怪獣 地球最大の決戦",
      transliteration: "San Daikaijū Chikyū Saidai No Kessen",
      translation: "Three Giant Monsters: Greatest Battle of Earth",
      aliases: "Ghidrah, the Three-Headed Monster",
      release_date: generate_date(1964, 12, 20),
      runtime: 93,
      preceded_by: {"Mothra vs. Godzilla", 1964},
      followed_by: {"Monster Zero", 1965},
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Screenplay", "Shinichi Sekizawa"},
        {"Photography", "Hajime Koizumi"},
        {"Art", "Takeo Kita"},
        {"Sound", "Fumio Yanoguchi"},
        {"Lighting", "Shoshichi Kojima"},
        {"Music", "Akira Ifukube"},
        {"Editor", "Ryohei Fujii"},
        {"Special Effects Photography", "Sadamasa Arikawa"},
        {"Special Effects Assistant Director", "Teruyoshi Nakano"}
      ],
      top_billed_cast: [
        {"Yosuke Natsuki", "Detective Shindo"},
        {"Yuriko Hoshi", "Naoko Shindo"},
        {"Hiroshi Koizumi", "Dr. Murai"},
        {"Takashi Shimura", "Dr. Tsukamoto"},
        {"The Peanuts", "The Shobijin"},
        {"Akiko Wakabayashi", "Princess Salno"},
        {"Hisaya Ito", "Malmess"},
        {"Susumu Kurobe", "Assassin"},
        {"Akihiko Hirata", "Chief Okita"},
        {"Kenji Sahara", "Newspaper Editor"},
        {"Toru Ibuki", "Assassin"},
        {"Kozo Nomura", "Geologist"},
        {"Yoshibumi Tajima", "Cruise Ship Captain"},
        {"Hideyo Amamoto", "Salno's Manservant"},
        {"Yoshio Kosugi", "Infant Island Chief"},
        {"Minoru Takada", "Defense Minister"},
        {"Yuriko Hanabusa", "Mrs. Shindo"},
        {"Haruya Kato", "Reporter"},
        {"Ikio Sawamura", "Fisherman"},
        {"Nakajiro Tomita", "General"},
        {"Shigeki Ishida", "Parliamentarian"},
        {"Shin Otomo", "Sergina Opposition Leader"},
        {"Yutaka Nakayama", "Mt. Aso Tourist"},
        {"Senkichi Omura", "Mt. Aso Tourist"},
        {"Somesho Matsumoto", "UFO Club President"},
        {"Kazuo Suzuki", "Assassin"},
        {"Senya Aozora", "TV Presenter"},
        {"Ichiya Aozora", "TV Presenter"},
        {"Shoichi Hirose", ["King Ghidorah", "Villager"]},
        {"Henry Okawa", "UFO Club Member"},
        {"Junichiro Mukai", "Parliamentarian"},
        {"Hideo Shibuya", ["Volcanologist", "Villager"]},
        {"Katsumi Tezuka", "Godzilla"},
        {"Koji Uno", "Hotel Clerk"},
        {"Takuzo Kumagai", "Parliamentarian"},
        {"Mitsuo Tsuda", "Parliamentarian"},
        {"Yoshio Katsube", "Reporter"},
        {"Kamayuki Tsubono", "Sailor"},
        {"Ken Echigo", "Bystander"},
        {"Yutaka Oka", "Dam Worker"},
        {"Haruo Nakajima", "Godzilla"},
        {"Haruya Sakamoto", "Geologist"}
      ],
      other_cast: [
        {"Kazuo Hinata", ["Serginan on Plane", "Parliamentarian", "Reporter"]},
        {"Minoru Ito", "Reporter"},
        {"Seishiro Kuno", "Waiter"},
        {"Akio Kusama", "Parliamentarian"},
        {"Junpei Natsuki", "UFO Club Member"},
        {"Tadashi Okabe", "Tsukamoto's Assistant"},
        {"Keiji Sakakida", "Serginan Official"},
        {"Masaki Shinohara", "Rodan"},
        {"Keisuke Yamada", "Prime Minister"}
      ],
      credits: generate_credits("ghidorah_the_three_headed_monster_1964"),
      synopsis: generate_synopsis("ghidorah_the_three_headed_monster_1964"),
      images: [
        "00191",
        "00221",
        "00293",
        "00336",
        "00592",
        "00661",
        "00904",
        "01043",
        "01093",
        "01136",
        "01157",
        "01164",
        "01193",
        "01291",
        "01326",
        "01442",
        "01462",
        "01484",
        "01621",
        "01797",
        "01831",
        "02012",
        "02051",
        "02069",
        "02270",
        "02411",
        "02494",
        "02530",
        "02547",
        "02583",
        "02635",
        "02656",
        "02697",
        "02783"
      ]
    }
  end
end
