defmodule BlargData.Films.GodzillaKingOfTheMonsters1954 do
  import DataUtil

  def get do
    %{
      title: "Godzilla, King of the Monsters",
      path: "godzilla-king-of-the-monsters-1954",
      original_title: "ゴジラ",
      transliteration: "Gojira",
      translation: "Godzilla",
      aliases: "Godzilla",
      release_date: generate_date(1954, 11, 3),
      runtime: 97,
      followed_by: {"Godzilla Raids Again", 1955},
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Original Story", "Shigeru Kayama"},
        {"Screenplay", ["Takeo Murata", "Ishiro Honda"]},
        {"Photography", "Masao Tamai"},
        {"Art Director", "Takeo Kita"},
        {"Sound", "Hisashi Shimonaga"},
        {"Lighting", "Choshiro Ishii"},
        {"Music", "Akira Ifukube"},
        {"Special Effects", "Eiji Tsuburaya"},
        {"Editor", "Kazuji Taira"}
      ],
      top_billed_cast: [
        {"Akira Takarada", "Hideto Ogata"},
        {"Momoko Kochi", "Emiko Yamane"},
        {"Akihiko Hirata", "Dr. Daisuke Serizawa"},
        {"Takashi Shimura", "Dr. Kyohei Yamane"},
        {"Fuyuki Murakami", "Dr. Tanabe"},
        {"Sachio Sakai", "Hagiwara"},
        {"Toranosuke Ogawa", "Fishing Company President"},
        {"Ren Yamamoto", "Masaji"},
        {"Kan Hayashi", "Diet Chairman"},
        {"Seijiro Onda", "Parliamentarian"},
        {"Takeo Oikawa", "Defense Secretary"},
        {"Keiji Sakakida", "Mayor Inada"},
        {"Toyoaki Suzuki", "Shinkichi"},
        {"Kuninori Kodo", "Izuma"},
        {"Kin Sugai", "Parliamentarian"},
        {"Shizuko Azuma", "Cruise Passenger"},
        {"Tadashi Okabe", "Yamane's Assistant"},
        {"Kiyoshi Kimata", "Cruise Passenger"},
        {"Ren Imaizumi", "Coast Guard"},
        {"Masaaki Tachibana", "Doomed Reporter"},
        {"Yasuhisa Tsutsumi", "Islander"},
        {"Saburo Iketani", "Reporter"},
        {"Katsumi Tezuka", ["Godzilla", "Newspaper Editor"]},
        {"Haruo Nakajima", ["Godzilla", "Newspaper Reporter"]}
      ],
      other_cast: [
        {"Ken Echigo", "Sailor"},
        {"Yu Fujiki", "Ship's Radio Operator"},
        {"Kazuo Hinata", ["Defense Official", "Radio Operator"]},
        {"Shoichi Hirose", "Parliamentarian"},
        {"Takuzo Kumagai", "Defense Official"},
        {"Sokichi Maki", "Coast Guard"},
        {"Junichiro Mukai", ["Reporter", "Defense Official"]},
        {"Junpei Natsuki", "Substation Operator"},
        {"Rinsaku Ogata", "Radio Operator"},
        {"Yutaka Sada", "Defense Official"},
        {"Kenji Sahara", ["Reporter", "Cruise Passenger"]},
        {"Akira Sera", "Parliamentarian"},
        {"Hideo Shibuya", "Reporter"},
        {"Kamayuki Tsubono", "Coast Guard"},
        {"Mitsuo Tsuda", "Policeman"},
        {"Koji Uno", "Correspondent"}
      ],
      credits: generate_credits("godzilla_king_of_the_monsters_1954"),
      synopsis: generate_synopsis("godzilla_king_of_the_monsters_1954"),
      images: [
        "00087",
        "00097",
        "00204",
        "00230",
        "00250",
        "00265",
        "00340",
        "00347",
        "00383",
        "00404",
        "00419",
        "00430",
        "00468",
        "00510",
        "00522",
        "00543",
        "00561",
        "00577",
        "00625",
        "00646",
        "00665",
        "00686",
        "00702",
        "00734",
        "00879",
        "00898",
        "00946",
        "00956",
        "00983",
        "01086",
        "01157",
        "01186",
        "01207",
        "01259",
        "01380",
        "01407",
        "01412",
        "01441",
        "01443",
        "01483",
        "01527",
        "01532",
        "01654",
        "01667",
        "01682",
        "01693",
        "01696",
        "01719",
        "01828",
        "01956",
        "01982",
        "02036",
        "02085",
        "02097",
        "02142",
        "02175",
        "02463",
        "02507",
        "02590",
        "02623",
        "02674",
        "02745",
        "02752",
        "02785",
        "02811",
        "02830",
        "02884"
      ]
    }
  end
end
