defmodule BlargData.Films.GodzillaVsTheSeaMonster1966 do
  import DataUtil

  def get do
    %{
      title: "Godzilla vs. the Sea Monster",
      path: "godzilla-vs-the-sea-monster-1966",
      original_title: "ゴジラ・エビラ・モスラ 南海の大決闘",
      transliteration: "Gojira Ebira Mosura Nankai No Daikettō",
      translation: "Godzilla, Ebirah, Mothra: South Seas Great Duel",
      aliases: "Ebirah, Horror of the Deep",
      release_date: generate_date(1966, 12, 17),
      runtime: 87,
      preceded_by: {"Monster Zero", 1965},
      followed_by: {"Son of Godzilla", 1967},
      produced_by: "Toho",
      staff: [
        {"Director", "Jun Fukuda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Screenplay", "Shinichi Sekizawa"},
        {"Photography", "Kazuo Yamada"},
        {"Art", "Takeo Kita"},
        {"Sound", "Shoichi Yoshizawa"},
        {"Lighting", "Norikazu Onda"},
        {"Music", "Masaru Sato"},
        {"Editor", "Ryohei Fujii"},
        {"Special Effects Co-Director", "Sadamasa Arikawa"},
        {"Special Effects Art", "Yasuyuki Inoue"},
        {"Special Effects Assistant Director", "Teruyoshi Nakano"}
      ],
      top_billed_cast: [
        {"Akira Takarada", "Yoshimura"},
        {"Kumi Mizuno", "Daiyo"},
        {"Akihiko Hirata", "Red Bamboo Captain Yamoto"},
        {"Jun Tazaki", "Red Bamboo Commander"},
        {"Hideo Sunazuka", "Nita"},
        {"Chotaro Togin", "Ichino"},
        {"Toru Ibuki", "Yata"},
        {"Toru Watanabe", "Ryota"},
        {"Hideyo Amamoto", "Red Bamboo Officer"},
        {"Ikio Sawamura", "Captive Islander"},
        {"Hisaya Ito", "Red Bamboo Scientist"},
        {"Shigeki Ishida", "Newspaper Editor"},
        {"Shoichi Hirose", "Escaped Islander"},
        {"Kazuo Suzuki", "Escaped Islander"},
        {"Yutaka Sada", "Villager"},
        {"Chieko Nakakita", "Yata's & Ryota's Mother"},
        {"Tadashi Okabe", "Red Bamboo Scientist"},
        {"Wataru Omae", "Reporter"},
        {"Kenichiro Maruyama", "Reporter"},
        {"Rinsaku Ogata", "Red Bamboo Soldier"},
        {"Yoshio Katsube", ["Captive Islander", "Red Bamboo Soldier"]},
        {"Hideo Shibuya", "Policeman"},
        {"Haruo Nakajima", "Godzilla"},
        {"Hiroshi Sekita", "Ebirah"},
        {"The Bambi Pair", "The Shobijin"}
      ],
      other_cast: [
        {"Yukihiko Gondo", "Red Bamboo Soldier"},
        {"Junpei Natsuki", "Captive Islander"}
      ],
      credits: generate_credits("godzilla_vs_the_sea_monster_1966"),
      synopsis: generate_synopsis("godzilla_vs_the_sea_monster_1966"),
      images: [
        "00056",
        "00213",
        "00252",
        "00334",
        "00414",
        "00437",
        "00556",
        "00564",
        "00625",
        "00751",
        "00868",
        "00929",
        "00934",
        "01089",
        "01124",
        "01170",
        "01357",
        "01562",
        "01616",
        "01935",
        "01964",
        "01985",
        "02154",
        "02168",
        "02226",
        "02228",
        "02264",
        "02280",
        "02411",
        "02437",
        "02504",
        "02563",
        "02591"
      ]
    }
  end
end
