defmodule BlargData.Films.GodzillaRaidsAgain1955 do
  import DataUtil

  def get do
    %{
      title: "Godzilla Raids Again",
      path: "godzilla-raids-again-1955",
      original_title: "ゴジラの逆襲",
      transliteration: "Gojira No Gyakushū",
      translation: "Counterattack of Godzilla",
      aliases: "Gigantis, the Fire Monster",
      release_date: generate_date(1955, 4, 24),
      runtime: 82,
      preceded_by: {"Godzilla, King of the Monsters", 1954},
      followed_by: {"King Kong vs. Godzilla", 1962},
      produced_by: "Toho",
      staff: [
        {"Director", "Motoyoshi Oda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Original Story", "Shigeru Kayama"},
        {"Screenplay", ["Takeo Murata", "Shigeaki Hidaka"]},
        {"Photography", "Seiichi Endo"},
        {"Art Director", "Takeo Kita"},
        {"Sound", "Masanobu Miyazaki"},
        {"Lighting", "Masaki Onuma"},
        {"Music", "Masaru Sato"},
        {"Editor", "Kazuji Taira"}
      ],
      top_billed_cast: [
        {"Hiroshi Koizumi", "Tsukioka"},
        {"Setsuko Wakayama", "Hidemi Yamaji"},
        {"Minoru Chiaki", "Kobayashi"},
        {"Takashi Shimura", "Dr. Kyohei Yamane"},
        {"Masao Shimizu", "Dr. Tadokoro"},
        {"Seijiro Onda", "Captain Terasawa"},
        {"Sonosuke Sawamura", "Branch Manager Shibeki"},
        {"Yoshio Tsuchiya", "Tajime"},
        {"Mayuri Mokusho", "Yasuko"},
        {"Minosuke Yamada", "Defense Secretary"},
        {"Yukio Kasama", "Mr. Yamaji"},
        {"Senkichi Omura", "Escaped Convict"},
        {"Ren Yamamoto", "Ikeda"},
        {"Shin Otomo", "Escaped Convict"},
        {"Shiro Tsuchiya", "Fishing Company Employee"},
        {"Takeo Oikawa", "Police Chief"},
        {"Sokichi Maki", "Escaped Convict"},
        {"Shoichi Hirose", "Escaped Convict"},
        {"Junpei Natsuki", "Escaped Convict"},
        {"Katsumi Tezuka", "Anguirus"},
        {"Haruo Nakajima", "Godzilla"},
        {"Miyoko Hoshino", "Nightclub Singer"}
      ],
      other_cast: [
        {"Tadao Nakamaru", "Policeman"},
        {"Keiji Sakakida", "Soldier"},
        {"Akira Sera", "Fishing Company Employee"},
        {"Masaaki Tachibana", "Policeman"},
        {"Koji Uno", "Assistant"}
      ],
      credits: generate_credits("godzilla_raids_again_1955"),
      synopsis: generate_synopsis("godzilla_raids_again_1955"),
      images: [
        "00059",
        "00108",
        "00126",
        "00242",
        "00280",
        "00298",
        "00415",
        "00497",
        "00615",
        "00703",
        "00773",
        "00812",
        "00914",
        "00930",
        "01042",
        "01052",
        "01074",
        "01087",
        "01106",
        "01139",
        "01350",
        "01367",
        "01387",
        "01425",
        "01480",
        "01522",
        "01638",
        "01789",
        "01928",
        "01991",
        "02147",
        "02178",
        "02191",
        "02284",
        "02306",
        "02307",
        "02343",
        "02354",
        "02390",
        "02402"
      ]
    }
  end
end
