defmodule BlargData.Films.Gorath1962 do
  import DataUtil

  def get do
    %{
      title: "Gorath",
      path: "gorath-1962",
      original_title: "妖星ゴラス",
      transliteration: "Yōsei Gorasu",
      translation: "Mystery Planet Gorath",
      release_date: generate_date(1962, 3, 21),
      runtime: 88,
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Original Story", "Jojiro Okami"},
        {"Screenplay", "Takeshi Kimura"},
        {"Photography", "Hajime Koizumi"},
        {"Art", ["Takeo Kita", "Teruaki Abe"]},
        {"Sound", "Toshiya Ban"},
        {"Lighting", "Toshio Takashima"},
        {"Music", "Kan Ishii"},
        {"Editor", "Reiko Kaneko"},
        {"Special Effects Photography", "Sadamasa Arikawa"}
      ],
      top_billed_cast: [
        {"Ryo Ikebe", "Dr. Tazawa"},
        {"Yumi Shirakawa", "Tomoko Sonoda"},
        {"Akira Kubo", "Tatsuma Kanai"},
        {"Kumi Mizuno", "Takiko Nomura"},
        {"Hiroshi Tachikawa", "Astronaut Wakabayashi"},
        {"Akihiko Hirata", "Captain Endo"},
        {"Kenji Sahara", "Lt. Saiki"},
        {"Jun Tazaki", "Captain Raizo Sonoda"},
        {"Ken Uehara", "Dr. Kono"},
        {"Takashi Shimura", "Dr. Keisuke Sonoda"},
        {"Seizaburo Kawazu", "Minister Tada"},
        {"Ko Mishima", "South Pole Engineer Sanada"},
        {"Sachio Sakai", "Doctor"},
        {"Takamaru Sasaki", "Prime Minister Seki"},
        {"Ko Nishimura", "Minister Murata"},
        {"Eitaro Ozawa", "Minister Kinami"},
        {"Masanari Nihei", "Astronaut Ito"},
        {"Kozo Nomura", "Satellite Commander"},
        {"Keiko Sata", "Secretary"},
        {"Hideyo Amamoto", "Barfly"},
        {"George Furness", "UN Ambassador"},
        {"Ross Bennett", "Gibson"},
        {"Junichiro Mukai", "Security Guard"},
        {"Nadao Kirino", "Lt. Manabe"},
        {"Fumio Sakashita", "Hayao Sonoda"},
        {"Ikio Sawamura", "Taxi Driver"},
        {"Rinsaku Ogata", "Spaceship Crew"},
        {"Tadashi Okabe", "Spaceship Crew"},
        {"Koji Uno", "Reporter"},
        {"Yukihiko Gondo", "Spaceship Crew"},
        {"Kenichiro Maruyama", "Spaceship Crew"},
        {"Yasuhiko Saijo", "Spaceship Crew"},
        {"Katsumi Tezuka", "Magma"},
        {"Wataru Omae", "Spaceship Crew"},
        {"Hideo Shibuya", "Reporter"},
        {"Takuzo Kumagai", "Minister"}
      ],
      other_cast: [
        {"Ken Echigo", "Satellite Crew"},
        {"Saburo Iketani", "TV Announcer"},
        {"Yoshio Katsube", ["Reporter", "Satellite Crew"]},
        {"Akio Kusama", "Minister"},
        {"Somesho Matsumoto", "Minister"},
        {"Yutaka Oka", "South Pole Crew"},
        {"Keiji Sakakida", "Minister"},
        {"Kamayuki Tsubono", "Minister"},
        {"Obel Wyatt", "UN Ambassador"},
        {"Keisuke Yamada", "Minister"},
        {"Osman Yusef", "South Pole Crew"}
      ],
      credits: generate_credits("gorath_1962"),
      synopsis: generate_synopsis("gorath_1962"),
      images: [
        "00121",
        "00296",
        "00392",
        "00586",
        "00790",
        "00936",
        "01092",
        "01237",
        "01253",
        "01296",
        "01323",
        "01361",
        "01387",
        "01566",
        "01669",
        "01814",
        "01820",
        "02036",
        "02354",
        "02422",
        "02493",
        "02548",
        "02627"
      ]
    }
  end
end
