defmodule BlargData.Films.HumanVapor1960 do
  import DataUtil

  def get do
    %{
      title: "The Human Vapor",
      path: "human-vapor-1960",
      original_title: "ガス人間第一号",
      transliteration: "Gasu Ningen Dai Ichigō",
      translation: "Gas Man No. 1",
      release_date: generate_date(1960, 12, 11),
      runtime: 91,
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Screenplay", "Takeshi Kimura"},
        {"Photography", "Hajime Koizumi"},
        {"Art", "Kiyoshi Shimizu"},
        {"Sound", ["Masao Fujiyoshi", "Masanobu Miyazaki"]},
        {"Lighting", "Toshio Takashima"},
        {"Special Effects Photography", "Sadamasa Arikawa"},
        {"Music", "Kunio Miyauchi"},
        {"Editor", "Kazuji Taira"}
      ],
      top_billed_cast: [
        {"Tatsuya Mihashi", "Detective Okamoto"},
        {"Kaoru Yachigusa", "Fujichiyo Kasuga"},
        {"Yoshio Tsuchiya", "Mizuno"},
        {"Keiko Sata", "Kyoko Kono"},
        {"Hisaya Ito", "Dr. Tamiya"},
        {"Yoshibumi Tajima", "Detective Tabata"},
        {"Yoshio Kosugi", "Detective Inao"},
        {"Fuyuki Murakami", "Dr. Sano"},
        {"Bokuzen Hidari", "Jiya"},
        {"Takamaru Sasaki", "Police Executive"},
        {"Minosuke Yamada", "Newspaper Executive"},
        {"Tatsuo Matsumura", "Newspaper Editor"},
        {"Yoyo Miyata", "Bank Official"},
        {"Ko Mishima", "Detective Fujita"},
        {"Kozo Nomura", "Reporter Kawasaki"},
        {"Ren Yamamoto", "Nishiyama"},
        {"Somesho Matsumoto", "Kasuga's Instructor"},
        {"Yasuhisa Tsutsumi", "Policeman"},
        {"Shoichi Hirose", "Jail Officer"},
        {"Tetsu Nakamura", "Newspaper Executive"},
        {"Toki Shiozawa", "Instructor's Wife"},
        {"Takuzo Kumagai", "Newspaper Executive"},
        {"Kamayuki Tsubono", "Detective Osaki"},
        {"Rinsaku Ogata", "Policeman"},
        {"Keiji Sakakida", "Jail Officer"},
        {"Yutaka Oka", "Man in Audience"},
        {"Keisuke Yamada", "Police Executive"},
        {"Yukihiko Gondo", "Detective Hotta"},
        {"Akio Kusama", "Police Executive"},
        {"Hideo Shibuya", "Banker"},
        {"Masaaki Tachibana", "Reporter"},
        {"Minoru Ito", "Reporter"},
        {"Wataru Omae", "Reporter"}
      ],
      other_cast: [
        {"Ken Echigo", "Scientist"},
        {"Kazuo Hinata", "Bank Official"},
        {"Yoshio Katsube", "Reporter"},
        {"Junpei Natsuki", "Reporter"},
        {"Haruo Suzuki", "Policeman"}
      ],
      credits: generate_credits("human_vapor_1960"),
      synopsis: generate_synopsis("human_vapor_1960"),
      images: [
        "00067",
        "00245",
        "00314",
        "00844",
        "00923",
        "00996",
        "01020",
        "01233",
        "01247",
        "01351",
        "01413",
        "01518",
        "01713",
        "01772",
        "01854",
        "02075",
        "02184",
        "02281",
        "02578",
        "02685",
        "02709",
        "02719"
      ]
    }
  end
end
