defmodule BlargData.Films.KingKongEscapes1967 do
  import DataUtil

  def get do
    %{
      title: "King Kong Escapes",
      path: "king-kong-escapes-1967",
      original_title: "キングコングの逆襲",
      transliteration: "Kingukongu No Gyakushū",
      translation: "Counterattack of King Kong",
      release_date: generate_date(1967, 7, 22),
      runtime: 104,
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Screenplay", "Takeshi Kimura"},
        {"Technical Adviser", "Arthur Rankin"},
        {"Photography", "Hajime Koizumi"},
        {"Art", "Takeo Kita"},
        {"Sound", "Shoichi Yoshizawa"},
        {"Lighting", "Toshio Takashima"},
        {"Music", "Akira Ifukube"},
        {"Editor", "Ryohei Fujii"},
        {"Special Effects Art", "Yasuyuki Inoue"},
        {"Special Effects Assistant Director", "Teruyoshi Nakano"}
      ],
      top_billed_cast: [
        {"Akira Takarada", "Lt. Jiro Nomura"},
        {"Mie Hama", "Madame Piranha"},
        {"Rhodes Reason", "Carl Nelson"},
        {"Linda Miller", "Susan Watson"},
        {"Hideyo Amamoto", "Dr. Who"},
        {"Yoshibumi Tajima", "Who Henchman"},
        {"Sachio Sakai", "Who Henchman"},
        {"Ikio Sawamura", "Islander"},
        {"Nadao Kirino", "Who Henchman"},
        {"Shoichi Hirose", "Submarine Crew"},
        {"Kazuo Suzuki", "Who Henchman"},
        {"Toru Ibuki", "Who Henchman"},
        {"Naoya Kusakawa", "Who Henchman"},
        {"Susumu Kurobe", "Who Henchman"},
        {"Haruo Nakajima", ["King Kong", "Bystander"]},
        {"Hiroshi Sekita", ["Mechani-Kong", "Gorosaurus"]}
      ],
      other_cast: [
        {"Kazuo Hinata", "Military Advisor"},
        {"Andrew Hughes", "UN Reporter"},
        {"Shigeo Kato", "Who Henchman"},
        {"Yoshio Katsube", "Who Henchman"},
        {"Seishiro Kuno", "Who Henchman"},
        {"Akio Kusama", "Soldier"},
        {"Rinsaku Ogata", "Submarine Crew"},
        {"Yutaka Oka", "Submarine Crew"},
        {"Tadashi Okabe", "Soldier"},
        {"Haruya Sakamoto", "Soldier"},
        {"Hideo Shibuya", "Submarine Crew"},
        {"Haruo Suzuki", "Who Henchman"},
        {"Masaaki Tachibana", "Soldier"},
        {"Kamayuki Tsubono", "Military Advisor"},
        {"Osman Yusef", "Submarine Crew"}
      ],
      credits: generate_credits("king_kong_escapes_1967"),
      synopsis: generate_synopsis("king_kong_escapes_1967"),
      images: [
        "00130",
        "00188",
        "00212",
        "00282",
        "00365",
        "00397",
        "00418",
        "00453",
        "00484",
        "00587",
        "00613",
        "00641",
        "00736",
        "00906",
        "01095",
        "01126",
        "01184",
        "01233",
        "01552",
        "01663",
        "01874",
        "02143",
        "02179",
        "02312",
        "02371",
        "02459",
        "02482",
        "02556",
        "02584",
        "02648",
        "02678",
        "02762",
        "02777",
        "02791",
        "02867",
        "03008",
        "03114"
      ]
    }
  end
end
