defmodule BlargData.Films.LastWar1961 do
  import DataUtil

  def get do
    %{
      title: "The Last War",
      path: "last-war-1961",
      original_title: "世界大戦争",
      transliteration: "Sekai Daisensō",
      translation: "World Great War",
      release_date: generate_date(1961, 10, 8),
      runtime: 110,
      produced_by: "Toho",
      staff: [
        {"Director", "Shue Matsubayashi"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", ["Sanezumi Fujimoto", "Tomoyuki Tanaka"]},
        {"Screenplay", ["Toshio Yasumi", "Takeshi Kimura"]},
        {"Photography", "Rokuro Nishigaki"},
        {"Art", ["Takeo Kita", "Teruaki Abe"]},
        {"Sound", "Fumio Yanoguchi"},
        {"Lighting", "Hiromitsu Mori"},
        {"Music", "Ikuma Dan"},
        {"Editor", "Koichi Iwashita"},
        {"Special Effects Photography", "Sadamasa Arikawa"}
      ],
      top_billed_cast: [
        {"Frankie Sakai", "Mokichi Tamura"},
        {"Akira Takarada", "Takano"},
        {"Yuriko Hoshi", "Saeko Tamura"},
        {"Nobuko Otowa", "Yoshi Tamura"},
        {"Yumi Shirakawa", "Sanae Ebara"},
        {"Chishu Ryu", "Ebara"},
        {"Jerry Ito", "Watkins"},
        {"Eijiro Tono", "Takano's Captain"},
        {"So Yamamura", "Prime Minister"},
        {"Ken Uehara", "Minister"},
        {"Seizaburo Kawazu", "Minister"},
        {"Nobuo Nakamura", "Cabinet Secretary"},
        {"Chieko Nakakita", "Ohara"},
        {"Minoru Takada", "Missile Defense Officer"},
        {"Shigeki Ishida", "Press Club Chauffeur"},
        {"Kozo Nomura", "Tamura's Stock Broker"},
        {"Yutaka Sada", "Reporter"},
        {"Nadao Kirino", "Missile Defense Officer"},
        {"Koji Uno", "Defense Officer"},
        {"Takuzo Kumagai", "Minister"},
        {"Soji Ubukata", "Minister"},
        {"Shiro Tsuchiya", "Minister"},
        {"Naoya Kusakawa", "Helicopter Crew"},
        {"Wataru Omae", "Sailor"},
        {"Yoshio Katsube", "Reporter"},
        {"Masaki Shinohara", "Defense Crew"},
        {"Yutaka Oka", "Defense Crew"},
        {"Harold S. Conway", "Federation Missile Commander"},
        {"Osman Yusef", "Alliance Pilot"}
      ],
      other_cast: [
        {"Ken Echigo", "TV Singer"},
        {"Kazuo Hinata", "Official"},
        {"Saburo Iketani", "TV Announcer"},
        {"Akio Kusama", "Press Club Chauffeur"},
        {"Masanari Nihei", "TV Singer"},
        {"Hiroshi Sekita", "TV Singer"},
        {"Hideo Shibuya", "Sailor"},
        {"Haruo Suzuki", "Defense Officer"},
        {"Masaaki Tachibana", ["Reporter", "Security Guard"]},
        {"Kamayuki Tsubono", "Press Club Chauffeur"},
        {"Obel Wyatt", "Alliance Officer"}
      ],
      credits: generate_credits("last_war_1961"),
      synopsis: generate_synopsis("last_war_1961"),
      images: [
        "00191",
        "00267",
        "00509",
        "00690",
        "00773",
        "00800",
        "00843",
        "01110",
        "01218",
        "01316",
        "01498",
        "01553",
        "01841",
        "01869",
        "01972",
        "02072",
        "02094",
        "02218",
        "02239",
        "02304",
        "02411",
        "02467",
        "02762",
        "02884",
        "02941",
        "02973",
        "03005",
        "03039",
        "03080",
        "03089",
        "03229",
        "03275"
      ]
    }
  end
end
