defmodule BlargData.Films.Mothra1961 do
  import DataUtil

  def get do
    %{
      title: "Mothra",
      path: "mothra-1961",
      original_title: "モスラ",
      transliteration: "Mosura",
      translation: "Mothra",
      release_date: generate_date(1961, 7, 30),
      runtime: 101,
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Original Story", ["Shinichiro Nakamura", "Takehiko Fukunaga", "Yoshie Hotta"]},
        {"Screenplay", "Shinichi Sekizawa"},
        {"Photography", "Hajime Koizumi"},
        {"Art", ["Takeo Kita", "Teruaki Abe"]},
        {"Sound", ["Shoichi Fujinawa", "Masanobu Miyazaki"]},
        {"Lighting", "Toshio Takashima"},
        {"Music", "Yuji Koseki"},
        {"Editor", "Kazuji Taira"},
        {"Special Effects Photography", "Sadamasa Arikawa"}
      ],
      top_billed_cast: [
        {"Frankie Sakai", "Senichiro Fukuda"},
        {"Hiroshi Koizumi", "Dr. Shinichi Chujo"},
        {"Kyoko Kagawa", "Michi Hanamura"},
        {"The Peanuts", "The Shobijin"},
        {"Jerry Ito", "Clark Nelson"},
        {"Ken Uehara", "Dr. Harada"},
        {"Akihiko Hirata", "Doctor"},
        {"Kenji Sahara", "Helicopter Pilot"},
        {"Seizaburo Kawazu", "General"},
        {"Takashi Shimura", "Newspaper Editor"},
        {"Yoshio Kosugi", "Ship's Captain"},
        {"Yoshibumi Tajima", "Soldier"},
        {"Ren Yamamoto", "Marooned Sailor"},
        {"Haruya Kato", "Marooned Sailor"},
        {"Tetsu Nakamura", "Nelson's Henchman"},
        {"Shoichi Hirose", "Dam Worker"},
        {"Yasuhisa Tsutsumi", "Expedition Member"},
        {"Mitsuo Tsuda", "Cruise Ship Captain"},
        {"Tadashi Okabe", "Expedition Member"},
        {"Akira Wakamatsu", "Nelson's Henchman"},
        {"Osman Yusef", "Nelson's Henchman"},
        {"Obel Wyatt", "Rolisican Mayor"},
        {"Harold S. Conway", "Rolisican Ambassador"},
        {"Robert Dunham", "Rolisican Policeman"},
        {"Koji Uno", "Policeman"},
        {"Wataru Omae", "Coast Guard"},
        {"Katsumi Tezuka", "Mothra"},
        {"Hideo Shibuya", "Reporter"},
        {"Kazuo Hinata", "Military Officer"},
        {"Shigeo Kato", "Dam Worker"},
        {"Rinsaku Ogata", "Fighter Pilot"},
        {"Yutaka Oka", "Pilot"},
        {"Yoshio Katsube", "Expedition Member"},
        {"Akio Kusama", "Soldier"},
        {"Haruo Nakajima", "Mothra"},
        {"Junpei Natsuki", "Evacuee"},
        {"Hiroshi Sekita", "Cruise Ship Helmsman"},
        {"Masaaki Tachibana", "Reporter"}
      ],
      other_cast: [
        {"Yukihiko Gondo", "Dam Worker"},
        {"Saburo Iketani", "Announcer"},
        {"Minoru Ito", "Soldier"},
        {"Masanari Nihei", "Policeman"},
        {"Keiji Sakakida", "Doctor"},
        {"Haruya Sakamoto", "Policeman"},
        {"Kamayuki Tsubono", "Soldier"}
      ],
      credits: generate_credits("mothra_1961"),
      synopsis: generate_synopsis("mothra_1961"),
      images: [
        "00113",
        "00207",
        "00246",
        "00288",
        "00426",
        "00495",
        "00553",
        "00586",
        "00641",
        "00774",
        "00807",
        "00824",
        "01027",
        "01105",
        "01107",
        "01146",
        "01202",
        "01394",
        "01602",
        "01716",
        "01817",
        "01821",
        "02129",
        "02391",
        "02463",
        "02718",
        "02724",
        "02867",
        "02902",
        "02946",
        "02966",
        "03001"
      ]
    }
  end
end
