defmodule BlargData.Films.MothraVsGodzilla1964 do
  import DataUtil

  def get do
    %{
      title: "Mothra vs. Godzilla",
      path: "mothra-vs-godzilla-1964",
      original_title: "モスラ対ゴジラ",
      transliteration: "Mosura Tai Gojira",
      translation: "Mothra Against Godzilla",
      release_date: generate_date(1964, 4, 29),
      runtime: 89,
      preceded_by: {"King Kong vs. Godzilla", 1962},
      followed_by: {"Ghidorah, the Three-Headed Monster", 1964},
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Screenplay", "Shinichi Sekizawa"},
        {"Photography", "Hajime Koizumi"},
        {"Art", "Takeo Kita"},
        {"Sound", "Fumio Yanoguchi"},
        {"Lighting", "Shoshichi Kojima"},
        {"Music", "Akira Ifukube"},
        {"Editor", "Ryohei Fujii"},
        {"Special Effects Photography", "Sadamasa Arikawa"},
        {"Special Effects Assistant Director", "Teruyoshi Nakano"}
      ],
      top_billed_cast: [
        {"Akira Takarada", "Ichiro Sakai"},
        {"Yuriko Hoshi", "Junko Nakanishi"},
        {"Hiroshi Koizumi", "Dr. Miura"},
        {"Yu Fujiki", "Jiro Nakamura"},
        {"Kenji Sahara", "Torahata"},
        {"The Peanuts", "The Shobijin"},
        {"Jun Tazaki", "Newspaper Editor"},
        {"Yoshibumi Tajima", "Kumayama"},
        {"Kenzo Tabu", "Industrial Park Developer"},
        {"Yutaka Sada", "School Principal"},
        {"Akira Tani", "Chief Fisherman"},
        {"Susumu Fujita", "General"},
        {"Ikio Sawamura", "Village Priest"},
        {"Ren Yamamoto", "Sailor"},
        {"Kozo Nomura", "Soldier"},
        {"Yasuhisa Tsutsumi", "Village Policeman"},
        {"Mitsuo Tsuda", "Soldier"},
        {"Shin Otomo", "Policeman"},
        {"Senkichi Omura", "Fisherman"},
        {"Yoshio Kosugi", "Infant Island Chief"},
        {"Miki Yashiro", "Schoolteacher"},
        {"Wataru Omae", "Kumayama's Henchman"},
        {"Shiro Tsuchiya", "Fisherman"},
        {"Takuzo Kuamgai", "Fisherman"},
        {"Koji Uno", "Fisherman"},
        {"Yutaka Nakayama", "Fisherman"},
        {"Hideo Shibuya", "Reporter"},
        {"Ken Echigo", "Reporter"},
        {"Yukihiko Gondo", "Kumayama's Henchman"},
        {"Tadashi Okabe", "Soldier"},
        {"Haruya Sakamoto", "Soldier"},
        {"Seishiro Kuno", "Soldier"},
        {"Keisuke Yamada", "Policeman"},
        {"Rinsaku Ogata", "Islander"},
        {"Haruo Suzuki", "Radio Operator"},
        {"Katsumi Tezuka", "Godzilla"},
        {"Haruo Nakajima", "Godzilla"}
      ],
      other_cast: [
        {"Harold S. Conway", "Military Advisor (American Version)"},
        {"Kazuo Hinata", "Reporter"},
        {"Yoshio Katsube", "Fisherman"},
        {"Kenichiro Maruyama", "Islander"},
        {"Junpei Natsuki", "Reporter"},
        {"Yutaka Oka", "Hotel Clerk"},
        {"Keiji Sakakida", "Islander"},
        {"Masaaki Tachibana", "Soldier"},
        {"Osman Yusef", "Reporter (American Version)"}
      ],
      credits: generate_credits("mothra_vs_godzilla_1964"),
      synopsis: generate_synopsis("mothra_vs_godzilla_1964"),
      images: [
        "00096",
        "00165",
        "00223",
        "00243",
        "00486",
        "00543",
        "00649",
        "00796",
        "00887",
        "00989",
        "01035",
        "01093",
        "01117",
        "01194",
        "01251",
        "01343",
        "01363",
        "01389",
        "01455",
        "01514",
        "01608",
        "01762",
        "01817",
        "01864",
        "01901",
        "01999",
        "02026",
        "02044",
        "02050",
        "02063",
        "02123",
        "02151",
        "02154",
        "02204",
        "02279",
        "02316",
        "02367",
        "02422",
        "02525",
        "02614"
      ]
    }
  end
end
