defmodule BlargData.Films.Mysterians1957 do
  import DataUtil

  def get do
    %{
      title: "The Mysterians",
      path: "mysterians-1957",
      original_title: "地球防衛軍",
      transliteration: "Chikyū Bōeigun",
      translation: "Earth Defense Force",
      release_date: generate_date(1957, 12, 28),
      runtime: 88,
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Original Story", "Jojiro Okami"},
        {"Screenplay", ["Shigeru Kayama", "Takeshi Kimura"]},
        {"Photography", "Hajime Koizumi"},
        {"Art", "Teruaki Abe"},
        {"Sound", "Masanobu Miyazaki"},
        {"Lighting", "Kuichiro Kishida"},
        {"Music", "Akira Ifukube"},
        {"Editor", "Koichi Iwashita"},
        {"Special Effects Photography", "Sadamasa Arikawa"}
      ],
      top_billed_cast: [
        {"Kenji Sahara", "Dr. Joji Atsumi"},
        {"Yumi Shirakawa", "Etsuko Shiraishi"},
        {"Momoko Kochi", "Hiroko Iwamoto"},
        {"Akihiko Hirata", "Dr. Ryoichi Shiraishi"},
        {"Takashi Shimura", "Dr. Tanjiro Adachi"},
        {"Susumu Fujita", "General Morita"},
        {"Hisaya Ito", "Officer Seki"},
        {"Yoshio Kosugi", "Officer Sugimoto"},
        {"Fuyuki Murakami", "Dr. Kawanami"},
        {"Yoshio Tsuchiya", "Grand Mysterian"},
        {"Minosuke Yamada", "Defense Secretary"},
        {"Tetsu Nakamura", "Dr. Koda"},
        {"Henry Okawa", "Translator"},
        {"Takeo Oikawa", "Newsreader"},
        {"Haruya Kato", "Villager"},
        {"Senkichi Omura", "Villager"},
        {"Yutaka Sada", "Policeman"},
        {"Hideo Mihara", "Military Officer"},
        {"Soji Ubukata", "Dr. Noda"},
        {"Mitsuo Tsuda", "Parliamentarian"},
        {"Ren Imaizumi", "Adachi's Assistant"},
        {"Shin Otomo", "Policeman"},
        {"Takuzo Kumagai", "Soldier"},
        {"Akio Kusama", "Policeman"},
        {"Shoichi Hirose", "Detective"},
        {"Tadao Nakamaru", "Soldier"},
        {"Kamayuki Tsubono", "Policeman"},
        {"Rinsaku Ogata", "Policeman"},
        {"George A. Furness", "Dr. Svenson"},
        {"Harold S. Conway", "Dr. DeGracia"},
        {"Haruo Nakajima", ["Mogera", "Soldier"]},
        {"Katsumi Tezuka", "Mogera"}
      ],
      other_cast: [
        {"Kazuo Hinata", "Pilot"},
        {"Minoru Ito", "Reporter"},
        {"Yoshio Katsube", "Reporter"},
        {"Junichiro Mukai", "Pilot"},
        {"Tadashi Okabe", "Soldier"},
        {"Keiji Sakakida", "Military Officer"},
        {"Hideo Shibuya", "Policeman"},
        {"Masaaki Tachibana", ["Soldier", "Policeman"]}
      ],
      credits: generate_credits("mysterians_1957"),
      synopsis: generate_synopsis("mysterians_1957"),
      images: [
        "00228",
        "00257",
        "00320",
        "00452",
        "00628",
        "00739",
        "00750",
        "00827",
        "00886",
        "00967",
        "01266",
        "01269",
        "01510",
        "01526",
        "01726",
        "01757",
        "01977",
        "01995",
        "02111",
        "02142",
        "02182",
        "02230",
        "02247",
        "02263",
        "02292",
        "02353",
        "02471",
        "02486",
        "02556",
        "02626",
        "02634",
        "02646"
      ]
    }
  end
end
