defmodule BlargData.Films.Rodan1956 do
  import DataUtil

  def get do
    %{
      title: "Rodan",
      path: "rodan-1956",
      original_title: "空の大怪獣ラドン",
      transliteration: "Sora No Daikaijū Radon",
      translation: "Giant Monster of Sky Rodan",
      release_date: generate_date(1956, 12, 26),
      runtime: 82,
      produced_by: "Toho",
      staff: [
        {"Director", "Ishiro Honda"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Original Story", "Ken Kuronuma"},
        {"Screenplay", ["Takeo Murata", "Takeshi Kimura"]},
        {"Photography", "Isamu Ashida"},
        {"Art", "Tatsuo Kita"},
        {"Sound", "Masanobu Miyazaki"},
        {"Lighting", "Shigeru Mori"},
        {"Music", "Akira Ifukube"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Assistant Director", "Jun Fukuda"},
        {"Editor", "Koichi Iwashita"}
      ],
      top_billed_cast: [
        {"Kenji Sahara", "Shigeru Kawamura"},
        {"Yumi Shirakawa", "Kiyo"},
        {"Akio Kobori", "Chief Nishimura"},
        {"Akihiko Hirata", "Dr. Kashiwagi"},
        {"Fuyuki Murakami", "Dr. Minami"},
        {"Minosuke Yamada", "Mining Chief Osaki"},
        {"Yoshibumi Tajima", "Izeki"},
        {"Fuminto Matsuo", "Dr. Hayama"},
        {"Akio Kusama", "Tsuda"},
        {"Hideo Mihara", "Air Force Commander"},
        {"Ren Imaizumi", "Dr. Sunagawa"},
        {"Rinsaku Ogata", "Goro"},
        {"Keiji Sakakida", "Miner"},
        {"Takuzo Kumagai", "Policeman"},
        {"Junichiro Mukai", "Air Force Officer"},
        {"Mitsuo Tsuda", "Air Force Officer"},
        {"Shoichi Hirose", ["Meganulon", "Pilot"]},
        {"Koji Uno", "Reporter"},
        {"Tadashi Okabe", "Reporter"},
        {"Yutaka Oka", "Pilot"},
        {"Masaaki Tachibana", "Policeman"},
        {"Yasuhisa Tsutsumi", "Pilot"},
        {"Haruya Sakamoto", "Miner"},
        {"Kamayuki Tsubono", ["Air Force Officer", "Police Chemist"]},
        {"Hideo Shibuya", "Miner"},
        {"Haruo Suzuki", "Coal Car Staff"},
        {"Ken Echigo", "Policeman"},
        {"Katsumi Tezuka", ["Meganulon", "Hotel Manager"]},
        {"Haruo Nakajima", ["Rodan", "Soldier"]}
      ],
      other_cast: [
        {"Saburo Iketani", "Newsreader"},
        {"Ren Yamamoto", "Soldier"}
      ],
      credits: generate_credits("rodan_1956"),
      synopsis: generate_synopsis("rodan_1956"),
      images: [
        "00069",
        "00194",
        "00215",
        "00331",
        "00417",
        "00537",
        "00782",
        "00879",
        "00912",
        "01001",
        "01111",
        "01299",
        "01373",
        "01413",
        "01547",
        "01663",
        "01680",
        "01900",
        "01928",
        "01950",
        "01974",
        "02005",
        "02016",
        "02150",
        "02170",
        "02242",
        "02300",
        "02331",
        "02367",
        "02380",
        "02386",
        "02421",
        "02430"
      ]
    }
  end
end
