defmodule BlargData.Films.SecretOfTheTelegian1960 do
  import DataUtil

  def get do
    %{
      title: "The Secret of the Telegian",
      path: "secret-of-the-telegian-1960",
      original_title: "電送人間",
      transliteration: "Densō Ningen",
      translation: "Electric Man",
      release_date: generate_date(1960, 4, 10),
      runtime: 85,
      produced_by: "Toho",
      staff: [
        {"Director", "Jun Fukuda"},
        {"Special Effects Director", "Eiji Tsuburaya"},
        {"Producer", "Tomoyuki Tanaka"},
        {"Screenplay", "Shinichi Sekizawa"},
        {"Photography", "Kazuo Yamada"},
        {"Art", "Kyoe Hamagami"},
        {"Sound", ["Yoshio Nishikawa", "Masanobu Miyazaki"]},
        {"Lighting", "Tsuruzo Nishikawa"},
        {"Music", "Sei Ikeno"},
        {"Special Effects Photography", "Sadamasa Arikawa"},
        {"Editor", "Kazuji Taira"}
      ],
      top_billed_cast: [
        {"Koji Tsuruta", "Kirioka"},
        {"Yumi Shirakawa", "Akiko Chujo"},
        {"Seizaburo Kawazu", "Onishi"},
        {"Yoshio Tsuchiya", "Detective Ozaki"},
        {"Tadao Nakamaru", "Tsudo"},
        {"Akihiko Hirata", "Detective Kobayashi"},
        {"Takamaru Sasaki", "Dr. Nikki"},
        {"Yoshibumi Tajima", "Takamasa"},
        {"Fuyuki Murakami", "Dr. Miura"},
        {"Ikio Sawamura", "Thriller Show Announcer"},
        {"Sachio Sakai", "Taki"},
        {"Shin Otomo", "Tsukamoto"},
        {"Ren Yamamoto", "Detective Marune"},
        {"Fuminto Matsuo", "Reporter"},
        {"Senkichi Omura", "Islander"},
        {"Yutaka Sada", "Policeman"},
        {"Akira Sera", "Caretaker"},
        {"Hideyo Amamoto", "Bodyguard"},
        {"Shoichi Hirose", "Bodyguard"},
        {"Nadao Kirino", "Bodyguard"},
        {"Shiro Tsuchiya", "Police Executive"},
        {"Takuzo Kumagai", "Tourist"},
        {"Tadashi Okabe", "Policeman"},
        {"Yutaka Nakayama", "Waiter"},
        {"Koji Uno", "Delivery Truck Driver"},
        {"Tatsuo Matsumura", "Newspaper Editor"},
        {"Yasuhisa Tsutsumi", "Reporter"},
        {"Yasuhiko Saijo", "Reporter"},
        {"Junichiro Mukai", "Police Executive"},
        {"Hideo Shibuya", "Policeman"}
      ],
      other_cast: [
        {"Ken Echigo", "Policeman"},
        {"Yukihiko Gondo", "Policeman"},
        {"Kazuo Hinata", "Waiter"},
        {"Minoru Ito", "Thriller Show Employee"},
        {"Yoshio Katsube", "Policeman"},
        {"Akio Kusama", "Police Executive"},
        {"Yutaka Oka", "Reporter"},
        {"Masaaki Tachibana", "Crime Scene Investigator"}
      ],
      credits: generate_credits("secret_of_the_telegian_1960"),
      synopsis: generate_synopsis("secret_of_the_telegian_1960"),
      images: [
        "00144",
        "00308",
        "00443",
        "00475",
        "00678",
        "00751",
        "00759",
        "00885",
        "00933",
        "01054",
        "01463",
        "01565",
        "01605",
        "01628",
        "01656",
        "01740",
        "01852",
        "01988",
        "02332",
        "02437",
        "02491",
        "02514",
        "02525",
        "02535"
      ]
    }
  end
end
